# Generated by Django 2.1.7 on 2019-04-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1500)),
                ('Year', models.CharField(max_length=1500)),
                ('Rated', models.CharField(max_length=1500)),
                ('Released', models.CharField(max_length=1500)),
                ('Runtime', models.CharField(max_length=1500)),
                ('Genre', models.CharField(max_length=1500)),
                ('Director', models.CharField(max_length=1500)),
                ('Writer', models.CharField(max_length=1500)),
                ('Actors', models.CharField(max_length=1500)),
                ('Plot', models.CharField(max_length=1500)),
                ('Language', models.CharField(max_length=1500)),
                ('Country', models.CharField(max_length=1500)),
                ('Awards', models.CharField(max_length=1500)),
                ('Poster', models.CharField(max_length=1500)),
                ('Metascore', models.CharField(max_length=1500)),
                ('imdbRating', models.CharField(max_length=1500)),
                ('imdbVotes', models.CharField(max_length=1500)),
                ('imdbID', models.CharField(max_length=1500)),
                ('Type', models.CharField(max_length=1500)),
                ('DVD', models.CharField(max_length=1500)),
                ('BoxOffice', models.CharField(max_length=1500)),
                ('Production', models.CharField(max_length=1500)),
                ('Website', models.CharField(max_length=1500)),
                ('Response', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=1500)),
                ('Value', models.CharField(max_length=1500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies_api.Movie')),
            ],
        ),
    ]
